package com.example.cowmjucraft.global.response.type;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum ErrorType {

    BAD_REQUEST(400, "COMMON_400_BAD_REQUEST", "잘못된 요청입니다."),
    INVALID_REQUEST(400, "COMMON_400_INVALID_REQUEST", "요청 형식이 올바르지 않습니다."),
    UNAUTHORIZED(401, "COMMON_401_UNAUTHORIZED", "인증이 필요합니다."),
    FORBIDDEN(403, "COMMON_403_FORBIDDEN", "접근 권한이 없습니다."),
    NOT_FOUND(404, "COMMON_404_NOT_FOUND", "요청한 리소스를 찾을 수 없습니다."),
    CONFLICT(409, "COMMON_409_CONFLICT", "요청이 현재 상태와 충돌합니다."),
    VALIDATION_FAILED(422, "COMMON_422_VALIDATION_FAILED", "요청 값 검증에 실패하였습니다."),
    INTERNAL_ERROR(500, "COMMON_500_INTERNAL_ERROR", "서버 내부 오류가 발생했습니다."),

    FORM_NOT_FOUND(404, "RECRUIT_404_FORM_NOT_FOUND", "폼을 찾을 수 없습니다."),
    FORM_QUESTION_NOT_FOUND(404, "RECRUIT_404_FORM_QUESTION_NOT_FOUND", "문항을 찾을 수 없습니다."),
    TARGET_FORM_NOT_FOUND(404, "RECRUIT_404_TARGET_FORM_NOT_FOUND", "대상 폼을 찾을 수 없습니다."),
    SOURCE_FORM_NOT_FOUND(404, "RECRUIT_404_SOURCE_FORM_NOT_FOUND", "원본 폼을 찾을 수 없습니다."),
    NOTICE_NOT_FOUND(404, "RECRUIT_404_NOTICE_NOT_FOUND", "공지사항을 찾을 수 없습니다."),
    APPLICATION_NOT_FOUND(404, "RECRUIT_404_APPLICATION_NOT_FOUND", "지원서를 찾을 수 없습니다."),

    INVALID_CREDENTIALS(401, "RECRUIT_401_INVALID_CREDENTIALS", "학번 또는 비밀번호가 올바르지 않습니다."),

    NOTICE_NOT_IN_THIS_FORM(400, "RECRUIT_400_NOTICE_NOT_IN_THIS_FORM", "해당 폼에 속한 공지사항이 아닙니다."),
    SOURCE_FORM_ID_REQUIRED(400, "RECRUIT_400_SOURCE_FORM_ID_REQUIRED", "sourceFormId가 필요합니다."),
    SOURCE_AND_TARGET_CANNOT_BE_SAME(400, "RECRUIT_400_SOURCE_AND_TARGET_CANNOT_BE_SAME", "sourceFormId와 targetFormId는 같을 수 없습니다."),
    COMMON_SECTION_CANNOT_HAVE_DEPARTMENT(400, "RECRUIT_400_COMMON_SECTION_CANNOT_HAVE_DEPARTMENT", "공통 섹션에는 부서가 있을 수 없습니다."),
    SELECT_OPTIONS_ONLY_FOR_SELECT(400, "RECRUIT_400_SELECT_OPTIONS_ONLY_FOR_SELECT", "선택형 문항에만 선택 옵션을 설정할 수 있습니다."),
    DEPARTMENT_TYPE_REQUIRED_FOR_DEPARTMENT_SECTION(400, "RECRUIT_400_DEPARTMENT_TYPE_REQUIRED_FOR_DEPARTMENT_SECTION", "부서 섹션에는 부서 타입이 필요합니다."),
    APPLICATION_NOT_IN_THIS_FORM(400, "RECRUIT_400_APPLICATION_NOT_IN_THIS_FORM", "해당 폼에 속한 지원서가 아닙니다."),
    FIRST_SECOND_DEPARTMENT_MUST_BE_DIFFERENT(400, "RECRUIT_400_FIRST_SECOND_DEPARTMENT_MUST_BE_DIFFERENT", "1지망과 2지망은 서로 달라야 합니다."),
    BOTH_DEPARTMENTS_REQUIRED(400, "RECRUIT_400_BOTH_DEPARTMENTS_REQUIRED", "1지망과 2지망을 모두 입력해야 합니다."),
    FORM_QUESTION_ID_REQUIRED(400, "RECRUIT_400_FORM_QUESTION_ID_REQUIRED", "formQuestionId가 필요합니다."),
    DUPLICATE_ANSWER(400, "RECRUIT_400_DUPLICATE_ANSWER", "중복된 답변이 존재합니다."),
    REQUIRED_ANSWER_MISSING(400, "RECRUIT_400_REQUIRED_ANSWER_MISSING", "필수 문항의 답변이 누락되었습니다."),
    ANSWER_FOR_UNSELECTED_DEPARTMENT(400, "RECRUIT_400_ANSWER_FOR_UNSELECTED_DEPARTMENT", "선택하지 않은 부서의 문항에 대한 답변입니다."),
    INVALID_SECTION_OR_DEPARTMENT_TYPE(400, "RECRUIT_400_INVALID_SECTION_OR_DEPARTMENT_TYPE", "섹션 또는 부서 정보가 올바르지 않습니다."),
    FORM_QUESTION_NOT_IN_THIS_FORM(400, "RECRUIT_400_FORM_QUESTION_NOT_IN_THIS_FORM", "해당 폼에 속한 문항이 아닙니다."),
    REQUIRED_ANSWER_CANNOT_BE_DELETED(400, "RECRUIT_400_REQUIRED_ANSWER_CANNOT_BE_DELETED", "필수 답변은 삭제할 수 없습니다."),

    RECRUITMENT_CLOSED(409, "RECRUIT_409_RECRUITMENT_CLOSED", "모집이 마감되었습니다."),
    DUPLICATE_STUDENT_ID(409, "RECRUIT_409_DUPLICATE_STUDENT_ID", "이미 제출된 학번입니다."),
    DUPLICATE_QUESTION_ORDER(409, "RECRUIT_409_DUPLICATE_QUESTION_ORDER", "문항 순서가 중복되었습니다.");

    private final int httpStatusCode;
    private final String code;
    private final String message;
}
