CREATE TABLE mail_outboxes (
    id BIGINT NOT NULL AUTO_INCREMENT,
    event_type ENUM('ORDER_VIEW_LINK','PAID_CONFIRMED','CANCELED','REFUND_REQUESTED','REFUNDED') NOT NULL,
    aggregate_id BIGINT NOT NULL,
    aggregate_version BIGINT NOT NULL,
    recipient VARCHAR(255) NOT NULL,
    buyer_name VARCHAR(100) NOT NULL,
    order_no VARCHAR(50) NOT NULL,
    view_url VARCHAR(1000) NOT NULL,
    reason VARCHAR(500),
    event_at DATETIME(6),
    deposit_deadline DATETIME(6),
    status ENUM('PENDING','PROCESSING','SENT','FAILED') NOT NULL,
    attempt_count INT NOT NULL,
    next_attempt_at DATETIME(6) NOT NULL,
    claimed_at DATETIME(6),
    claim_token VARCHAR(36),
    sent_at DATETIME(6),
    last_error VARCHAR(1000),
    created_at DATETIME(6),
    updated_at DATETIME(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_mail_outboxes_event_aggregate_version (event_type, aggregate_id, aggregate_version),
    KEY idx_mail_outboxes_status_next_attempt (status, next_attempt_at)
) ENGINE=InnoDB;
